language: node_js
node_js:
  - 10
cache: yarn
before_install:
  - yarn global add makeshift && makeshift -r https://registry.npmjs.org
install:
  - yarn install
script:
  - yarn build
deploy:
  - provider: npm
    skip_cleanup: true
    email: ken@gizzar.com
    api_key: $NPM_TOKEN
    tag: latest
    on:
      tags: true
